default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: pocket_pal_development

test:
  <<: *default
  database: pocket_pal_test

production:
  <<: *default
  database: pocket_pal
